# Generated by Django 4.2.27 on 2025-12-22 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=64, unique=True)),
                ("customer_email", models.EmailField(db_index=True, max_length=254)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_keys",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "license_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("seat_limit", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="licenses.licensekey",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="brands.product",
                    ),
                ),
            ],
            options={
                "db_table": "licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instance_id", models.CharField(max_length=255)),
                ("instance_name", models.CharField(blank=True, max_length=255)),
                ("instance_metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="licenses.license",
                    ),
                ),
            ],
            options={
                "db_table": "activations",
                "ordering": ["-activated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["customer_email"], name="license_key_custome_dc5384_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["brand", "customer_email"],
                name="license_key_brand_i_466ce2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["status"], name="licenses_status_c60f55_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["expires_at"], name="licenses_expires_d6ad63_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="license",
            unique_together={("license_key", "product")},
        ),
        migrations.AddIndex(
            model_name="activation",
            index=models.Index(
                fields=["instance_id"], name="activations_instanc_93a23c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activation",
            index=models.Index(
                fields=["is_active"], name="activations_is_acti_ae5a13_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activation",
            unique_together={("license", "instance_id")},
        ),
    ]
